version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
      - run: sudo apt-get update
      - run: sudo apt-get install libmpich-dev mpich
      - run: pip install --user h5py scipy numpy mpi4py pytest dill pytest-timeout pytest-mpi
      - run: pytest -m "not slow"
