version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
      - run: sudo apt-get update
      - run: sudo apt-get install libmpich-dev mpich
      - run: pip install --user h5py scipy numpy mpi4py pytest 
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#version: 2.1
# Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs
#workflows:
#  # Name the workflow "welcome"
#  welcome:
#    # Run the welcome/run job in its own container
#    jobs:
#      - welcome/run
